### ISSUE TITLE
Add wikilink capacity to elements defined by title

### ISSUE THREAD

**Issue by Ravenclawer** [coddingtonbear/obsidian-itinerary#10]
This is a great plugin, I wonder if you could make the title in wikilink format clickable in the calendar view, so that it has the extended capacity to link to other notes

**Comment by Ravenclawer** [comment]
This issue is overlapped with #1,i will close it if the feature released in the future update

**Comment by coddingtonbear** [comment]
That does sound like a neat feature -- are you willing to post a pull request adding it; I'd totally be up for reviewing such a thing.

**Comment by coddingtonbear** [comment]
Definitely feel free to start a discussion via the "Discussions" panel if you're looking for somebody to implement this for you.  Cheers & good luck!
