### ISSUE TITLE
[feature request] using  code blocks  in itinerary-event in other notes as data sources for the calendar view

### ISSUE THREAD

**Issue by Ravenclawer** [coddingtonbear/obsidian-itinerary#11]
Add an option to use data more than in one note, maybe using data in the whole vault with specific tags/folders/wikilinks , maybe using dataview syntax could do this

**Comment by coddingtonbear** [comment]
This exists already -- if you glance at the readme for this repository, you'll see that `source` allows you to specify the documents from which to source event data.
