### ISSUE TITLE
Itinerary Events not showing inside calendar

### ISSUE THREAD

**Issue by greatwillow** [coddingtonbear/obsidian-itinerary#12]
Hi!  I was just testing the itinerary plugin with the example code provided in the documentation, however I am unable to see the itinerary events populating the calendar.  I believe that this would be a bug since I had copy pasted the code from the docs into a new document.  Any thoughts on this one?  Thanks!

![Screen Shot 2022-02-06 at 2 57 47 PM](https://user-images.githubusercontent.com/15651001/152699129-774578db-56dd-4001-a11b-90a16ca381b7.png)

**Comment by coddingtonbear** [comment]
Not likely to be a bug since it's still working in my repo!  I should say, though, that it's pretty much impossible for me to guess what's going on if you don't provide the exact markdown of your document.

**Comment by greatwillow** [comment]
Ah yes, found the issue, and you're correct, it was on my end.  Sorry for not including the code though it was copied directly from the Obsidan doc so didn't think it was necessary.  Copying the code directly from github solved the issue.  

It turns out my copy had included a space after ```itinerary-event which was causing the code block to not be recognized.  I suppose this is a little gotcha with markdown that I hadn't encountered before.   Hopefully this will help someone else if they run into the same issue.

Nonetheless, thanks for the response.  Nice plugin!

**Comment by coddingtonbear** [comment]
Awesome, I'm glad you got it sorted out!  I'm sort of surprised that the space would cause such a problem, but as long as you got it working, that's all that matters.  Cheers!
