### ISSUE TITLE
event color options

### ISSUE THREAD

**Issue by pcause** [coddingtonbear/obsidian-itinerary#13]
Full calendar supports eventBackgroundColor and eventTextColor.  If I am in dark mode and use Gold as the color, the text is white and hard to read.  I tried setting the full color options and they aren't accepted.  You might add code to pass through these if specified or some equivalent.

**Comment by coddingtonbear** [comment]
I'm afraid that all properties are already passed-through (I, in fact, use that particular behavior for some of my own itineraries) -- you can see that here: https://github.com/coddingtonbear/obsidian-itinerary/blob/master/src/render.ts#L93.  The particular problem _you're_ running into is that we explicitly set background colors per-event, and if one isn't specified, we use a default value as you'll see around here: https://github.com/coddingtonbear/obsidian-itinerary/blob/master/src/extractor.ts#L46.

You're welcome to start a discussion in the discussions tab about how you might change the behavior to be better suited for your needs; we could then talk through what that might look like.  Unfortunately, though, the onus of actually doing the work would be on you or your ability to convince somebody else into helping you put together a pull request.  So, if you're interested in talking that over and helping put that together, definitely feel free to start a discussion on the "Discussions" tab.

Cheers!

**Comment by pcause** [comment]
i looked at the source and I could use textColor and that worked.
