### ISSUE TITLE
multiple sources

### ISSUE THREAD

**Issue by pcause** [coddingtonbear/obsidian-itinerary#14]
I want to have the source be the file that I am displaying, plus 2 other files.  I tried:

"[[fulll/path/this file]] [[full/path/elsewhere/file]] [[full/path/yetanother/stuff]]"

and it dodt display events from the other files and actually lost events in the calendar from the base file.  Can you clarify the README:

A)  Will the base file always be included in the calendar display and overall display
B) What is syntax for multiple files in multiple locations in the vault

Thanks.

**Comment by coddingtonbear** [comment]
Hey there -- sorry, @pcause, but please open feature requests and questions in the "Discussions" tab.  Issues on this project are for bugs & planned projects.

Cheers!
