### ISSUE TITLE
time only events

### ISSUE THREAD

**Issue by pcause** [coddingtonbear/obsidian-itinerary#16]
Very small change.  I'd like start and end to to have only a time entered and have the event treated as for the current day.  Idea is that in extractor.ts you check if the first character of the start is a 'T" and if so you prepend the current date:

>if (parsed.start[0] = 'T') {
>    parsed.start = DateTime.toISODate() + parsed.start;
>}

and the same for the end.

The idea is that a "time only" is in the format THH:MM, where HH is 0 leading hour and MM is 0 leading minute and the code just adds the date and we have an ISO date-time.

**Comment by coddingtonbear** [comment]
Hey there @pcause -- please post feature requests as discussions under the "Discussions" tab -- you might even find somebody there who'd be willing to help you put a pull request together.  On this project, "Issues" are reserved for bugs and committed work.
