### ISSUE TITLE
Ability to constrain width/height of calendar

### ISSUE THREAD

**Issue by mbafford** [coddingtonbear/obsidian-itinerary#18]
Obsidian v.0.13.23
Calendar Version 1.5.10
New editor mode (not legacy)
Readable line length setting: OFF

I have an ultra-wide monitor, and have "readable line length" turned off, so sometimes end up with absurdly large width allocated to the calendar. 

This means that the calendar will end up being so tall (it looks like it uses a square aspect ratio for sizing?) that I have to scroll a fair amount to get from the top to the bottom of the calendar. This is unfortunate in month view, and kind of ridiculous in week view, since most of the space is empty space.

It would be nice to have a max width/height constraint that can be applied to the calendar - maybe a custom CSS setting to add to the calendar code-block?

e.g., when using "listWeek", I have more than 1 page of just blank space:

![image](https://user-images.githubusercontent.com/713813/155249248-c549da52-5c98-4976-b864-8b1c62e90ee7.png)

**Comment by coddingtonbear** [comment]
Hey there @mbafford -- please post feature requests via the "Discussions" tab.  On this project, "Issues" Is used only for tracking bugs and committed work.

Cheers!
