### ISSUE TITLE
Rendering for events lasting multiple days broken with Obsidian 1.0 update

### ISSUE THREAD

**Issue by oneVR** [coddingtonbear/obsidian-itinerary#22]
Previously working itineraries now have events lasting multiple days cut and only displayed in one cell after updating to Obsidian 1.0.

![image](https://user-images.githubusercontent.com/4764355/196016093-bd9e3068-c4bc-451a-9bd3-910c8fbbad1b.png)

**Comment by Tian-hy** [comment]
I have the same issue and do not know how to fix it.

**Comment by coddingtonbear** [comment]
This and #23 are both documenting a bug almost certainly caused by the same problem.  I'm going to close this one since the other issue has had more activity.

**Comment by KzBeck** [comment]
I have the same issue
