### ISSUE TITLE
mis-spellings

### ISSUE THREAD

**Issue by lwb52** [coddingtonbear/obsidian-itinerary#7]
the correct spelling is "itenerary"—it is spelled as "Itinterary" in the title and "itinerary" in the filename…

**Comment by coddingtonbear** [comment]
Whoops -- could you file a pull request fixing those misspellings?  I'd love to merge it if so!

**Comment by lwb52** [comment]
just tried, but too newbish to accomplish that!

really don't want to mess w⁄ all the various places that word is used, cause if i miss one or more, it might screw up the code…

**Comment by coddingtonbear** [comment]
I _believe_ I've fixed the one misspelling of itinerary in a1bd55d now, but let me know if you saw another place where this was incorrect.
